<a href="https://colab.research.google.com/github/muyiwa-obadara/AIPlanetProjects/blob/main/EDA/Quiz_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quiz - [AIPlanet](https://aiplanet.com/learn)

This notebook is used to answer the [Exam Score dataset](https://raw.githubusercontent.com/dphi-official/Datasets/master/exam_scores.csv) quiz.

In [ ]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/exam_scores.csv")

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group B,bachelor's degree,standard,none,74,68,67
1,female,group C,some college,standard,completed,58,68,66
2,male,group C,some college,free/reduced,none,66,65,65
3,female,group D,bachelor's degree,free/reduced,none,74,75,73
4,male,group D,some college,standard,none,78,77,71
...,...,...,...,...,...,...,...,...
995,female,group C,some high school,standard,none,68,77,72
996,female,group E,some college,standard,none,98,81,94
997,female,group E,associate's degree,free/reduced,none,67,67,67
998,female,group C,high school,standard,none,63,68,70
999,male,group C,some college,free/reduced,none,49,57,50

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
df["reading score"].isnull().mean()

0.0